package com.atguigu.imperial.court.mapper;

import com.atguigu.imperial.court.entity.Memorials;
import com.atguigu.imperial.court.entity.MemorialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemorialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    long countByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int deleteByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int deleteByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int insert(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int insertSelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    List<Memorials> selectByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    Memorials selectByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int updateByExample(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int updateByPrimaryKeySelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    int updateByPrimaryKey(Memorials record);
}