package com.atguigu.imperial.court.entity;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_id
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_name
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_position
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    private String empPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.login_account
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.login_password
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    private String loginPassword;


    // Mybatis 逆向工程生成的实体类只有字段和 get、set 方法，我们可以自己添加无参构造器、有参构造器、toString() 方法。
    public Emp() {
    }

    public Emp(Integer empId, String empName, String empPosition, String loginAccount, String loginPassword) {
        this.empId = empId;
        this.empName = empName;
        this.empPosition = empPosition;
        this.loginAccount = loginAccount;
        this.loginPassword = loginPassword;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", empPosition='" + empPosition + '\'' +
                ", loginAccount='" + loginAccount + '\'' +
                ", loginPassword='" + loginPassword + '\'' +
                '}';
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_id
     *
     * @return the value of t_emp.emp_id
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_id
     *
     * @param empId the value for t_emp.emp_id
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_name
     *
     * @return the value of t_emp.emp_name
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_name
     *
     * @param empName the value for t_emp.emp_name
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_position
     *
     * @return the value of t_emp.emp_position
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public String getEmpPosition() {
        return empPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_position
     *
     * @param empPosition the value for t_emp.emp_position
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public void setEmpPosition(String empPosition) {
        this.empPosition = empPosition == null ? null : empPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.login_account
     *
     * @return the value of t_emp.login_account
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.login_account
     *
     * @param loginAccount the value for t_emp.login_account
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.login_password
     *
     * @return the value of t_emp.login_password
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.login_password
     *
     * @param loginPassword the value for t_emp.login_password
     *
     * @mbg.generated Tue Jan 02 15:58:59 CST 2024
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }
}